name: 'Add reviewer to the PR'
description: 'Adds reviewers to the PR'
branding:
  icon: "check-circle"
  color: "purple"
inputs:
  reviewers:  
    description: 'Comma separated reviewers Id(s)'
    required: true
    default: 'World'
  token:
    description: "Github access token"
    required: true
  debugMode:
    description: "Prints logs when debug-mode is set to true"
    required: false
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
